# Generated by Django 4.1.2 on 2022-11-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_answer_body_alter_question_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user_id',
            new_name='profile_id',
        ),
    ]
