# Generated by Django 4.1.2 on 2022-11-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_answer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerrating',
            name='value',
            field=models.IntegerField(choices=[('1', 'Like'), ('-1', 'Dislike')]),
        ),
        migrations.AlterField(
            model_name='questionrating',
            name='value',
            field=models.IntegerField(choices=[('1', 'Like'), ('-1', 'Dislike')]),
        ),
    ]
