# Generated by Django 4.1.2 on 2022-11-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_answerrating_value_alter_questionrating_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tag',
            new_name='tags',
        ),
    ]
