# Generated by Django 4.1.2 on 2022-11-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_user_id_answerrating_profile_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answerrating',
            index=models.Index(fields=['answer_id', 'profile_id'], name='app_answerr_answer__bf98f3_idx'),
        ),
        migrations.AddIndex(
            model_name='questionrating',
            index=models.Index(fields=['question_id', 'profile_id'], name='app_questio_questio_cd4514_idx'),
        ),
        migrations.AddConstraint(
            model_name='answerrating',
            constraint=models.UniqueConstraint(fields=('answer_id', 'profile_id'), name='Users can`t add more than one rating for answer'),
        ),
        migrations.AddConstraint(
            model_name='questionrating',
            constraint=models.UniqueConstraint(fields=('question_id', 'profile_id'), name='Users can`t add more than one rating for question'),
        ),
    ]
