# Generated by Django 4.1.2 on 2022-11-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_answerrating_app_answerr_answer__bf98f3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerrating',
            name='value',
            field=models.SmallIntegerField(choices=[('1', 'Like'), ('-1', 'Dislike')]),
        ),
        migrations.AlterField(
            model_name='questionrating',
            name='value',
            field=models.SmallIntegerField(choices=[('1', 'Like'), ('-1', 'Dislike')]),
        ),
    ]
