# Generated by Django 4.1.2 on 2022-11-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_answerrating_value_alter_questionrating_value'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answerrating',
            name='Users can`t add more than one rating for answer',
        ),
        migrations.RemoveConstraint(
            model_name='questionrating',
            name='Users can`t add more than one rating for question',
        ),
        migrations.RemoveIndex(
            model_name='answerrating',
            name='app_answerr_answer__bf98f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='questionrating',
            name='app_questio_questio_cd4514_idx',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answerrating',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='answerrating',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='questionrating',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='questionrating',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddIndex(
            model_name='answerrating',
            index=models.Index(fields=['answer', 'profile'], name='app_answerr_answer__ff3c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='questionrating',
            index=models.Index(fields=['question', 'profile'], name='app_questio_questio_0cd6cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='answerrating',
            constraint=models.UniqueConstraint(fields=('answer', 'profile'), name='Users can`t add more than one rating for answer'),
        ),
        migrations.AddConstraint(
            model_name='questionrating',
            constraint=models.UniqueConstraint(fields=('question', 'profile'), name='Users can`t add more than one rating for question'),
        ),
    ]
