# Generated by Django 4.1.2 on 2022-11-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_answerrating_users can`t add more than one rating for answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='aboba@mail.com', max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='aboba', max_length=30),
            preserve_default=False,
        ),
    ]
