# Generated by Django 4.1.2 on 2022-11-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_userprofile_email_alter_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['rating'], name='app_answer_rating_0fa57b_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['rating'], name='app_questio_rating_ef1c4c_idx'),
        ),
    ]
