# Generated by Django 4.1.2 on 2022-11-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_answer_rating_question_answer_num_question_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
